### ISSUE TITLE
Refactor E2E tests to cover all our supported setups

### ISSUE THREAD

**Issue by MatteoJoliveau** [oxidrive/oxidrive#50]
Currently, we run E2E tests by building a temporary docker image of Oxidrive and starting it with Postgres via docker-compose. This not only doesn't allow to easily change the configuration to test more scenarios (e.g. test with SQlite, or with S3), but it also requires rebuilding the image on every parallel run (we currently test multiple browsers in parallel).

We should refactor the E2E CI step to wait for the unstable build to be finished, then start a matrix of jobs with:
```yaml
matrix:
    project: ['chromium', 'firefox', 'webkit', 'Mobile Chrome', 'Mobile Safari']
    database: ['postgresql', 'sqlite']
    storage: ['filesystem', 'minio']
```

This would create 20 parallel jobs with all the combinations we want to ensure Oxidrive works with. The only downside is that we need to publish unstable builds before they have been tested to be able to pull the image, but I'd say it's ok since they are, well... unstable 😄
